theme: jekyll-theme-minimal
title: WakeFintech's Website
description: This site hosts the latest information behind what's happening on campus around Blockchain and Financial Technology
github_username: brockly
logo: /Wake_Fintech_Logo.png
